# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import container_maker_spec.types_pb2 as types__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ContainerMakerAPIStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.listContainer = channel.unary_unary(
                '/containermaker.ContainerMakerAPI/listContainer',
                request_serializer=types__pb2.ListContainerRequest.SerializeToString,
                response_deserializer=types__pb2.ListContainerResponse.FromString,
                _registered_method=True)
        self.createContainer = channel.unary_unary(
                '/containermaker.ContainerMakerAPI/createContainer',
                request_serializer=types__pb2.CreateContainerRequest.SerializeToString,
                response_deserializer=types__pb2.ContainerResponse.FromString,
                _registered_method=True)
        self.getContainer = channel.unary_unary(
                '/containermaker.ContainerMakerAPI/getContainer',
                request_serializer=types__pb2.GetContainerRequest.SerializeToString,
                response_deserializer=types__pb2.ContainerResponse.FromString,
                _registered_method=True)
        self.deleteContainer = channel.unary_unary(
                '/containermaker.ContainerMakerAPI/deleteContainer',
                request_serializer=types__pb2.DeleteContainerRequest.SerializeToString,
                response_deserializer=types__pb2.DeleteContainerResponse.FromString,
                _registered_method=True)
        self.saveContainer = channel.unary_unary(
                '/containermaker.ContainerMakerAPI/saveContainer',
                request_serializer=types__pb2.SaveContainerRequest.SerializeToString,
                response_deserializer=types__pb2.SaveContainerResponse.FromString,
                _registered_method=True)


class ContainerMakerAPIServicer(object):
    """Missing associated documentation comment in .proto file."""

    def listContainer(self, request, context):
        """*
        List all containers within the network.
        Takes in a ListContainerRequest and returns ListContainerResponse.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def createContainer(self, request, context):
        """*
        Gets or Creates a container on the running environment.
        Takes in a CreateContainerRequest and returns ContainerResponse.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getContainer(self, request, context):
        """*
        Get a container.
        Takes in a GetContainerRequest and returns ContainerResponse.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def deleteContainer(self, request, context):
        """*
        Delete a container.
        Takes in a DeleteContainerRequest and returns DeleteContainerResponse.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def saveContainer(self, request, context):
        """*
        Save a container.
        Takes in a SaveContainerRequest and returns SaveContainerResponse.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ContainerMakerAPIServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'listContainer': grpc.unary_unary_rpc_method_handler(
                    servicer.listContainer,
                    request_deserializer=types__pb2.ListContainerRequest.FromString,
                    response_serializer=types__pb2.ListContainerResponse.SerializeToString,
            ),
            'createContainer': grpc.unary_unary_rpc_method_handler(
                    servicer.createContainer,
                    request_deserializer=types__pb2.CreateContainerRequest.FromString,
                    response_serializer=types__pb2.ContainerResponse.SerializeToString,
            ),
            'getContainer': grpc.unary_unary_rpc_method_handler(
                    servicer.getContainer,
                    request_deserializer=types__pb2.GetContainerRequest.FromString,
                    response_serializer=types__pb2.ContainerResponse.SerializeToString,
            ),
            'deleteContainer': grpc.unary_unary_rpc_method_handler(
                    servicer.deleteContainer,
                    request_deserializer=types__pb2.DeleteContainerRequest.FromString,
                    response_serializer=types__pb2.DeleteContainerResponse.SerializeToString,
            ),
            'saveContainer': grpc.unary_unary_rpc_method_handler(
                    servicer.saveContainer,
                    request_deserializer=types__pb2.SaveContainerRequest.FromString,
                    response_serializer=types__pb2.SaveContainerResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'containermaker.ContainerMakerAPI', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('containermaker.ContainerMakerAPI', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ContainerMakerAPI(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def listContainer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/containermaker.ContainerMakerAPI/listContainer',
            types__pb2.ListContainerRequest.SerializeToString,
            types__pb2.ListContainerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def createContainer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/containermaker.ContainerMakerAPI/createContainer',
            types__pb2.CreateContainerRequest.SerializeToString,
            types__pb2.ContainerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getContainer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/containermaker.ContainerMakerAPI/getContainer',
            types__pb2.GetContainerRequest.SerializeToString,
            types__pb2.ContainerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def deleteContainer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/containermaker.ContainerMakerAPI/deleteContainer',
            types__pb2.DeleteContainerRequest.SerializeToString,
            types__pb2.DeleteContainerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def saveContainer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/containermaker.ContainerMakerAPI/saveContainer',
            types__pb2.SaveContainerRequest.SerializeToString,
            types__pb2.SaveContainerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
