# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import container_maker_spec.types_pb2 as types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x0e\x63ontainermaker\x1a\x0btypes.proto2\xe9\x03\n\x11\x43ontainerMakerAPI\x12\\\n\rlistContainer\x12$.containermaker.ListContainerRequest\x1a%.containermaker.ListContainerResponse\x12\\\n\x0f\x63reateContainer\x12&.containermaker.CreateContainerRequest\x1a!.containermaker.ContainerResponse\x12V\n\x0cgetContainer\x12#.containermaker.GetContainerRequest\x1a!.containermaker.ContainerResponse\x12\x62\n\x0f\x64\x65leteContainer\x12&.containermaker.DeleteContainerRequest\x1a\'.containermaker.DeleteContainerResponse\x12\\\n\rsaveContainer\x12$.containermaker.SaveContainerRequest\x1a%.containermaker.SaveContainerResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONTAINERMAKERAPI']._serialized_start=47
  _globals['_CONTAINERMAKERAPI']._serialized_end=536
# @@protoc_insertion_point(module_scope)
